---
title: "p8105_hw6_yx3033"
output: github_document
---
```{r, message=FALSE}
library(tidyverse)
```


## Problem 1
```{r}
homi_raw = read_csv("hw6_data/homicide-data.csv")
```

```{r}
homicide_df =
  homi_raw |>
  mutate(
    city_state = paste(city, state, sep = ", "),
    #solved = 1
    solve_binary = if_else(disposition == "Closed by arrest", 1, 0)
  ) |>
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", 
                       "Kansas City, MO", "Tulsa, AL")
  ) |>
  filter(
    victim_race %in% c("White", "Black")  
  ) |>
  mutate(
    victim_age = as.numeric(victim_age)
  )

```


```{r}
baltimore_df = 
  homicide_df |> 
  filter(city_state == "Baltimore, MD")

glm_md = glm(
  solve_binary ~ victim_age + victim_sex + victim_race,
  data = baltimore_df,
  family = binomial()
)

glm_md_tidy =
  glm_md |> 
  broom::tidy(conf.int = TRUE, exponentiate = TRUE)

male_or =
  glm_md_tidy |> 
  filter(term == "victim_sexMale") |> 
  select(term, estimate, conf.low, conf.high)

male_or
```
After adjusting for victim age and race, homicides involving male victims had significantly lower odds of being solved compared to those involving female victims (adjusted OR = 0.426, 95% CI: 0.324–0.558).


```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(broom)
```

```{r}
city_results =
  homicide_df |> 
  group_by(city_state) |> 
  nest() |> 
  mutate(
    # fit glm for each city
    model = map(data, ~ glm(
      solve_binary ~ victim_age + victim_sex + victim_race,
      data = .x,
      family = binomial()
    )),
    
    # tidy model results with OR and CI
    tidied = map(model, ~ tidy(
      .x,
      conf.int = TRUE,
      exponentiate = TRUE
    ))
  ) |>
  unnest(tidied) |> 
  filter(term == "victim_sexMale") |> 
  select(
    city_state,
    estimate,
    conf.low,
    conf.high
  )
```

```{r}
library(ggplot2)
```


```{r}
city_results_plot =
  ggplot(city_results, 
       aes(x = estimate, y = reorder(city_state, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Adjusted Odds Ratio (Male vs Female Victims)",
    y = "City",
    title = "Adjusted OR by City"
  ) +
  theme_minimal()

city_results_plot
```













